### ISSUE TITLE
Adding IIR filters

### ISSUE THREAD

**Issue by TristanCacqueray** [Simre1/lambdasound#2]
Hello, first of all, thank you for making this package, it's looking great!

I'm trying to add some filters, and you mentioned IIR in the 'modifyWholeSound' documentation. Though I don't get it because if I understand correctly, IIR are applied one sample at a time, so I'm not sure that is correct.

So, would it be possible to have a `Traversable (Sound d)` instance? For what it's worth, I made some IIR designs in this [simple-dsp](https://github.com/TristanCacqueray/simple-dsp/blob/main/src/SimpleDSP/IIR.hs#L97) library, and I think they could be used like this:

```haskell
simpleFilter :: IIRParams -> Sound T Pulse -> Sound T Pulse
simpleFilter params = snd . mapAccumL applyFilter initialIIRState
  where
    applyFilter :: IIRState -> Pulse -> (IIRState, Pulse)
    applyFilter state (Pulse sample) =
      let newState = applyIIR params sample state
       in (newState, Pulse newState.y0)
```

**Comment by Simre1** [comment]
Hello, I hope I can clarify what I mean with IRR filters.

Here is the function `modifyWholeSound`:
```haskell
modifyWholeSound :: M.Load r M.Ix1 Pulse => 
    (M.Vector M.S Pulse -> M.Vector r Pulse) -> 
    Sound d Pulse -> 
    Sound d Pulse
```
The array `M.Vector M.S Pulse` contains all the samples of the input sound and `M.Vector r Pulse` is where you write the output samples. So you can generate each output sample while looking at all the input samples. If you create the output samples `M.Vector r Pulse` in a mutable manner (ST), you can also access output samples already generated. That's why I think IRR filters should be possible.

There are some caveats currently: The input and output vector have to have the same length, though this is not checked right now and will be made safer in the future. There may also still be some bugs, I haven't checked every behavior yet.

In the future, I might add some convenience function which help to create filters. If you design your own filters, I will be happy to incorporate them when you create a PR.

`Traversable (Sound d)` will most likely not be possible with the current implementation. Of course, you can use `modifyWholeSound` again to work with a `massiv` vector which is traversable.

**Comment by Simre1** [comment]
@TristanCacqueray 

I have found the time to incorporate what you have done in the `simple-dsp` library in [this branch](https://github.com/Simre1/lambdasound/compare/irr-filters). Maybe you can give be some feedback if this corresponds with what you are trying to do.

Also, I have troubles figuring out if this works correctly since I know only a little about filters. Can you try this out? It would also be great if you can add some additional documentation about the different parameters since I do not know what they mean.

**Comment by TristanCacqueray** [comment]
Nice, that sounds about right to me. I also know only a little about filters, I guess the parameters are the cutoff frequency and the resonance?

For a nicer result it would be nice to adjust the filter frequency with the note so that the effect is stable across the different pitch. And I think we would need to apply an envelop too.

**Comment by Simre1** [comment]
I have now added additional features:
- Changing the pitch also changes the filter frequency accordingly
- It is possible to create filters with an arbitrary amount of coefficients

I do not really know how I would apply an envelope to the filter, so I do not think I can do that.

All the features I want at the moment are implemented now. Do you have some additional ideas or can this be closed?

**Comment by TristanCacqueray** [comment]
I think you can apply an envelop to the filter by sweeping the frequency, e.g. by having the sustain be the desired cutoff. The envelope is usually controlled by an amount ranging from -1 to 1 to indicate the sweep direction. That can result in some interesting effect.

**Comment by Simre1** [comment]
Alright, I think I get it now. Thanks for the clarification!

Although applying an envelope to a filter is not possible right now, I will still close this issue. IIR filters are added to the library so this issue is done in my mind.

Regarding the envelope for the filter, I have created [a more specific issue here](https://github.com/Simre1/lambdasound/issues/3). If this is something you want asap, you can comment there.
